QuanLyNhanVien/QuanLyNhanVien/Controllers/NhanVienController.cs
using QuanLyNhanVien.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace QuanLyNhanVien.Controllers
{
    public class NhanVienController : Controller
    {
        // GET: NhanVien
        public ActionResult Index(string searchString, int? page)
        {

            var listNhanVien = new QuanLyNhanVienConnectionString().NhanVien.ToList();

            //Phan trang
            if (page == null) page = 1;
            int pageSize = 5;
            int pageNumber = (page ?? 1);


            //Tim kiem
            ViewBag.Keyword = searchString;

            if(!String.IsNullOrEmpty(searchString))
            {
                listNhanVien = listNhanVien.Where(a => a.HoVaTen.Contains(searchString)).ToList();

            }    

            return View(listNhanVien.ToPagedList(pageNumber, pageSize));
        }

        // GET: NhanVien/Details/5
        public ActionResult Details(int id)
        {
            var context = new QuanLyNhanVienConnectionString();
            var detailNhanVien = context.NhanVien.Find(id);
            var chucVuSelectItem = new SelectList(context.ChucVu, "Id", "TenChucVu");
            ViewBag.IdChucVu = chucVuSelectItem;

            return View(detailNhanVien);
        }

        // GET: NhanVien/Create
        public ActionResult Create()
        {
            var context = new QuanLyNhanVienConnectionString();
            var chucVuSelectItem = new SelectList(context.ChucVu, "Id", "TenChucVu");
            ViewBag.IdChucVu = chucVuSelectItem;
            return View();
        }

        // POST: NhanVien/Create
        [HttpPost]
        public ActionResult Create(NhanVien model)
        {
            try
            {
                // TODO: Add insert logic here
                var context = new QuanLyNhanVienConnectionString(); 
                context.NhanVien.Add(model);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: NhanVien/Edit/5
        public ActionResult Edit(int id)
        {
            var context = new QuanLyNhanVienConnectionString(); 
            var editNhanVien = context.NhanVien.Find(id);
            var chucVuSelectItem = new SelectList(context.ChucVu, "Id", "TenChucVu", editNhanVien.IdChucVu);
            ViewBag.IdChucVu = chucVuSelectItem;

            return View(editNhanVien);
        }

        // POST: NhanVien/Edit/5
        [HttpPost]
        public ActionResult Edit(NhanVien model)
        {
            try
            {
                // TODO: Add update logic here
                var context = new QuanLyNhanVienConnectionString();
                var oldItem = context.NhanVien.Find(model.Id);
                oldItem.HoVaTen = model.HoVaTen;
                oldItem.ChucVu = model.ChucVu;
                oldItem.CMND = model.CMND;
                oldItem.GioiTinh = model.GioiTinh;
                oldItem.Email = model.Email;
                oldItem.DiaChi = model.DiaChi;
                oldItem.SoDienThoai = model.SoDienThoai;
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: NhanVien/Delete/5
        public ActionResult Delete(int id)
        {
            var context = new QuanLyNhanVienConnectionString();
            var deleteNhanVien = context.NhanVien.Find(id);

            return View(deleteNhanVien);
        }

        // POST: NhanVien/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                var context = new QuanLyNhanVienConnectionString();
                var deleteNhanVien = context.NhanVien.Find(id);
                context.NhanVien.Remove(deleteNhanVien);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

QuanLyNhanVien/QuanLyNhanVien/Views/NhanVien/Create.cshtml
@model QuanLyNhanVien.Models.NhanVien

@{
    ViewBag.Title = "Create";


}

<h2>Thêm mới nhân viên</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Họ và Tên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoVaTen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoVaTen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Giới tính", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.GioiTinh)
                    @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Địa chỉ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Địa chỉ Email", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Số điện thoại", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoDienThoai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoDienThoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CMND, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CMND, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CMND, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Chức vụ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdChucVu", null, "--Chọn Chức Vụ--", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdChucVu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Thêm nhân viên" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Danh sách nhân viên", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QuanLyNhanVien/QuanLyNhanVien/Views/NhanVien/Delete.cshtml
@model QuanLyNhanVien.Models.NhanVien

@{
    ViewBag.Title = "Delete";
    
}

<h2>Xóa nhân viên</h2>

<h3>Bạn có chắc muốn xóa nhân viên này?</h3>
<div>
    <h4>Nhân viên:</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.Display("Họ và Tên")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoVaTen)
        </dd>

        <dt>
            @Html.Display("Giới tính")
        </dt>

        <dd>
            @(Model.GioiTinh?"Nam":"Nữ")
        </dd>

        <dt>
            @Html.Display("Địa chỉ")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
           @Html.Display("Địa chỉ Email")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.Display("Số điện thoại")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoDienThoai)
        </dd>

        <dt>
            @Html.Display("Số CMND")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CMND)
        </dd>

        <dt>
            @Html.Display("Chức vụ")
        </dt>

        <dd>
            @(Model.ChucVu==null?"":Model.ChucVu.TenChucVu)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <input type="hidden" id="id" value="@Model.Id"/>
        <div class="form-actions no-color">
            <input type="submit" value="Xóa nhân viên" class="btn btn-default" /> |
            @Html.ActionLink("Danh sách nhân viên", "Index")
        </div>
    }
</div>

QuanLyNhanVien/QuanLyNhanVien/Views/NhanVien/Details.cshtml
@model QuanLyNhanVien.Models.NhanVien

@{
    ViewBag.Title = "Details";
    
}

<h2>Thông tin chi tiết</h2>

<div>
    <h4>Nhân viên:</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Họ và Tên")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoVaTen)
        </dd>

        <dt>
            @Html.DisplayName("Giới tính")
        </dt>

        <dd>
            @(Model.GioiTinh?"Nam":"Nữ")
        </dd>

        <dt>
            @Html.DisplayName("Địa chỉ")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChi)
        </dd>

        <dt>
            @Html.DisplayName("Địa chỉ Email")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayName("Số điện thoại")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoDienThoai)
        </dd>

        <dt>
            @Html.DisplayName("Số CMND")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CMND)
        </dd>

        <dt>
            @Html.DisplayName("Chức vụ")
        </dt>

        <dd>
            @(Model.ChucVu == null ? "" : Model.ChucVu.TenChucVu)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Sửa", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Danh sách nhân viên", "Index")
</p>

QuanLyNhanVien/QuanLyNhanVien/Views/NhanVien/Edit.cshtml
@model QuanLyNhanVien.Models.NhanVien

@{
    ViewBag.Title = "Edit";
}

<h2>Chỉnh sửa thông tin</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Nhân viên:</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.Label("Họ và Tên", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoVaTen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoVaTen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Giới tính", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.GioiTinh)
                    @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Địa chỉ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DiaChi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DiaChi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Địa chỉ Email", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Số điện thoại", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SoDienThoai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SoDienThoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Số CMND", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CMND, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CMND, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Chức vụ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdChucVu", null, "--Chọn Chức Vụ--", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IdChucVu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cập nhật" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Danh sách nhân viên", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

QuanLyNhanVien/QuanLyNhanVien/Views/NhanVien/Index.cshtml
@model PagedList.IPagedList<QuanLyNhanVien.Models.NhanVien>

@using PagedList.Mvc

@{
    ViewBag.Title = "Index";
   
}

<h2>Danh sách nhân viên</h2>

<p>
    @Html.ActionLink("Thêm mới nhân viên", "Create")
</p>

<div>
    @using (Html.BeginForm("Index", "NhanVien", FormMethod.Get))
    {
        <div class="row">
            <div class="align-content-lg-center">
                <div class="col-md-2">
                    <input type="text" value="@ViewBag.Keyword" name="searchString" />

                </div>
                <div class="col-md-2">
                    <button type="submit">Tìm kiếm</button>

                </div>

            </div>

        </div>
    }
</div>

<br />

<table class="table">
    <tr>
        <th>
            Họ Và Tên
        </th>
        <th>
           Gới tính
        </th>
        <th>
            @Html.Display("Địa Chỉ")
        </th>
        <th>
            @Html.Display("Địa Chỉ Email")
        </th>
        <th>
            @Html.Display("Số Điện Thoại")
        </th>
        <th>
            @Html.Display("Chứng Minh Thư")
        </th>
        <th>
            @Html.Display("Chức Vụ")
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.HoVaTen)
            </td>
            <td>
                @(item.GioiTinh?"Nam":"Nữ")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiaChi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoDienThoai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CMND)
            </td>
            <td>
                @(item.ChucVu==null?"":item.ChucVu.TenChucVu)
            </td>
            <td>
                @Html.ActionLink("Sửa", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Chi tiết", "Details", new { id = item.Id }) |
                @Html.ActionLink("Xóa", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

<br />
Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index", new { page, @searchString = ViewBag.Keyword}))